# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-01 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20, verbose_name='游戏名')),
                ('gtype', models.SmallIntegerField(choices=[(0, 'MOBA'), (1, 'FPS'), (2, 'RPG')], default=0, verbose_name='游戏类型')),
                ('gpub_date', models.DateField(verbose_name='发布时间')),
                ('gpalyer', models.IntegerField(default=0, verbose_name='玩家数量')),
                ('gis_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
            ],
            options={
                'db_table': 'tb_games',
                'verbose_name_plural': '游戏',
                'verbose_name': '游戏',
            },
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20, verbose_name='英雄名')),
                ('hgender', models.SmallIntegerField(choices=[(0, 'MAN'), (1, 'WOMEN')], default=0, verbose_name='性别')),
                ('hskill', models.CharField(max_length=20, verbose_name='技能')),
                ('his_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('hgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.GameInfo', verbose_name='所属游戏')),
            ],
            options={
                'db_table': 'tb_heros',
                'verbose_name_plural': '英雄',
                'verbose_name': '英雄',
            },
        ),
    ]
